CPU = samd5x
CPU_MODEL = samd51p19a

# FEATURES_PROVIDED += highlevel_stdio
# FEATURES_PROVIDED += periph_dac
FEATURES_PROVIDED += periph_i2c
FEATURES_PROVIDED += periph_rtc
# FEATURES_PROVIDED += periph_rtt
# FEATURES_PROVIDED += periph_pwm
FEATURES_PROVIDED += periph_spi
FEATURES_PROVIDED += periph_timer
FEATURES_PROVIDED += periph_uart
# FEATURES_PROVIDED += periph_adc
FEATURES_PROVIDED += periph_usbdev

